spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tour_manager
    username: postgres
    password: myuser
    driver-class-name: org.postgresql.Driver

  jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  devtools:
      restart:
        enabled: true
      livereload:
        enabled: true

